export const MODIFY_ORGANISATION_NAME =
  "multisafe/organisation/MODIFY_ORGANISATION_NAME";
export const MODIFY_ORGANISATION_NAME_SUCCESS =
  "multisafe/organisation/MODIFY_ORGANISATION_NAME_SUCCESS";
export const MODIFY_ORGANISATION_NAME_ERROR =
  "multisafe/organisation/MODIFY_ORGANISATION_NAME_ERROR";
