export const NETWORK_NAMES = {
  LOCAL: "LOCAL",
  RINKEBY: "RINKEBY",
  ROPSTEN: "ROPSTEN",
  KOVAN: "KOVAN",
  MAINNET: "MAINNET",
  POLYGON: "POLYGON",
};

export const CHAIN_IDS = {
  [NETWORK_NAMES.MAINNET]: 1,
  [NETWORK_NAMES.ROPSTEN]: 3,
  [NETWORK_NAMES.RINKEBY]: 4,
  [NETWORK_NAMES.KOVAN]: 42,
  [NETWORK_NAMES.POLYGON]: 137,
};

export const NETWORK_NAME_BY_ID = {
  [CHAIN_IDS[NETWORK_NAMES.MAINNET]]: NETWORK_NAMES.MAINNET,
  [CHAIN_IDS[NETWORK_NAMES.RINKEBY]]: NETWORK_NAMES.RINKEBY,
  [CHAIN_IDS[NETWORK_NAMES.POLYGON]]: NETWORK_NAMES.POLYGON,
};
