export const CREATE_MULTISIG_TRANSACTION =
  "multisafe/multisig/CREATE_MULTISIG_TRANSACTION";
export const CREATE_MULTISIG_TRANSACTION_SUCCESS =
  "multisafe/multisig/CREATE_MULTISIG_TRANSACTION_SUCCESS";
export const CREATE_MULTISIG_TRANSACTION_ERROR =
  "multisafe/multisig/CREATE_MULTISIG_TRANSACTION_ERROR";

export const CONFIRM_MULTISIG_TRANSACTION =
  "multisafe/multisig/CONFIRM_MULTISIG_TRANSACTION";
export const CONFIRM_MULTISIG_TRANSACTION_SUCCESS =
  "multisafe/multisig/CONFIRM_MULTISIG_TRANSACTION_SUCCESS";
export const CONFIRM_MULTISIG_TRANSACTION_ERROR =
  "multisafe/multisig/CONFIRM_MULTISIG_TRANSACTION_ERROR";

export const SUBMIT_MULTISIG_TRANSACTION =
  "multisafe/multisig/SUBMIT_MULTISIG_TRANSACTION";
export const SUBMIT_MULTISIG_TRANSACTION_SUCCESS =
  "multisafe/multisig/SUBMIT_MULTISIG_TRANSACTION_SUCCESS";
export const SUBMIT_MULTISIG_TRANSACTION_ERROR =
  "multisafe/multisig/SUBMIT_MULTISIG_TRANSACTION_ERROR";

export const GET_MULTISIG_TRANSACTIONS =
  "multisafe/multisig/GET_MULTISIG_TRANSACTIONS";
export const GET_MULTISIG_TRANSACTIONS_SUCCESS =
  "multisafe/multisig/GET_MULTISIG_TRANSACTIONS_SUCCESS";
export const GET_MULTISIG_TRANSACTIONS_ERROR =
  "multisafe/multisig/GET_MULTISIG_TRANSACTIONS_ERROR";

export const GET_MULTISIG_TRANSACTION_BY_ID =
  "multisafe/multisig/GET_MULTISIG_TRANSACTION_BY_ID";
export const GET_MULTISIG_TRANSACTION_BY_ID_SUCCESS =
  "multisafe/multisig/GET_MULTISIG_TRANSACTION_BY_ID_SUCCESS";
export const GET_MULTISIG_TRANSACTION_BY_ID_ERROR =
  "multisafe/multisig/GET_MULTISIG_TRANSACTION_BY_ID_ERROR";

export const CLEAR_MULTISIG_TRANSACTION =
  "multisafe/multisig/CLEAR_MULTISIG_TRANSACTION";
