# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coinshift frontend CI/CD Deployment

on:
  push:
    branches: [ master, staging, integration ]
  pull_request:
    branches: [ master, staging, integration ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check for integration server
      if: github.ref == 'refs/heads/integration' && github.event_name == 'push'
      run: |
        echo Deploying on integration servers
        cd
        /root/integration-server.sh
